version: 2

requirements:
  signed_off_by:
    required: false
    
group_defaults:
   approve_by_comment:
      approve_regex: ^Approved
      enabled: true
      reject_regex: ^Rejected
   reset_on_push:
      enabled: false
    
groups:

  Owner:
    required: 1
    users:
    - FunnyBuddys
    teams:
    - owners
      
  Software:
      required: 1
      users:
      - FunnyBuddys
      - AppleDevelops
      teams:
      - software
